"""Build a BLIND hand-labeling sheet to measure how often the LLM judge agrees
with a human.

Every number in the benchmark depends on judge_real_outcomes.py's LLM judge
answering three questions per case. One judge bug already moved the headline
by ~12 points, and nothing has ever checked the judge against a person. This
script prepares ~150 cases for the person to label, hiding the judge's own
answers (they go in a separate key file) so the labels are independent.

The sheet shows, per case: the facts, what the REAL court decided, and what the
AI decided (relief type, amount, full order -- regenerated by re-running the
scripted pipeline on the CURRENT code, so it is byte-identical to what the
judge saw provided the verdict file was produced by this same code). Cases are
drawn evenly across the judge's own three verdicts (match / partial /
mismatch) so the labeler sees the hard, disputed calls and not just easy
matches. Only cases the pipeline resolved are eligible (escalated ones have no
AI decision to compare).

Labeler fills three columns per row (Y / N):
  claimant_prevailed_ai    did the claimant (whoever brought the claim) get real relief under the AI decision?
  claimant_prevailed_real  did the SAME claimant get real relief under the real court's decision?
  relief_similar           only if both are Y: is the relief comparable in type and amount (amount within ~20%)? else leave blank

Then: python -m scripts.judge_human_agreement --labels <filled.csv>

Run (from backend/):
  DIGINYAYA_EVAL_DATASET=data_cache/eval_sample.json python -m scripts.build_human_label_sheet \\
      --verdicts data_cache/sample_verdicts_fixed.json --n 150
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, ".")

from scripts.judge_real_outcomes import run_and_capture  # noqa: E402
from scripts.run_real_judgment_eval import DATASET_PATH  # noqa: E402

DATA = Path(__file__).resolve().parent.parent / "data_cache"
GOOD = ("match", "partial", "mismatch")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verdicts", required=True)
    ap.add_argument("--n", type=int, default=150)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--sheet", default=str(DATA / "human_label_sheet.csv"))
    ap.add_argument("--key", default=str(DATA / "human_label_key.json"))
    args = ap.parse_args()

    cases = {c["case_id"]: c for c in json.loads(DATASET_PATH.read_text(encoding="utf-8"))}
    verdicts = [v for v in json.loads(Path(args.verdicts).read_text(encoding="utf-8"))
                if v.get("verdict") in GOOD and v["case_id"] in cases]
    rng = random.Random(args.seed)
    per = args.n // 3
    chosen: list[dict] = []
    for kind in GOOD:
        pool = [v for v in verdicts if v["verdict"] == kind]
        chosen.extend(rng.sample(pool, min(per, len(pool))))
    rng.shuffle(chosen)

    rows, key = [], {}
    for v in chosen:
        case = cases[v["case_id"]]
        ai = run_and_capture(case)
        if ai is None:
            continue
        rows.append({
            "case_id": case["case_id"],
            "facts": case["case_description"],
            "REAL_COURT_DECIDED": case["expected_outcome"],
            "AI_DECIDED_relief_type": ai.get("relief_type"),
            "AI_DECIDED_amount": ai.get("relief_amount_display"),
            "AI_DECIDED_order": " ".join(ai.get("order") or []),
            "claimant_prevailed_ai": "",
            "claimant_prevailed_real": "",
            "relief_similar": "",
        })
        key[case["case_id"]] = {
            "claimant_prevailed_ai": v["claimant_prevailed_ai"],
            "claimant_prevailed_real": v["claimant_prevailed_real"],
            "relief_similar": v.get("relief_similarity") == "similar",
            "verdict": v["verdict"],
            "judge_prompt_hash": v.get("judge_prompt_hash"),
        }

    with open(args.sheet, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    Path(args.key).write_text(json.dumps(key, indent=2), encoding="utf-8")
    print(f"Wrote {len(rows)} blind rows -> {args.sheet}")
    print(f"Judge's answers (do NOT open before labeling) -> {args.key}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
