"""Formalize the error analysis of the real-judgment eval into a repo-checked
report: a confusion-matrix-style breakdown by dispute category, an
escalation-safety-gate breakdown, and a classification of WHY each non-match
verdict happened (reusing the judge's own free-text reason -- not
re-litigating each case from scratch).

Reads the same three artifacts scripts/train_outcome_classifier.py does:
  - data_cache/eval_judgments_with_signals.json  (46 cases, category/language)
  - data_cache/real_judgment_eval_results.json   (46 cases, pipeline run metadata)
  - data_cache/real_judgment_verdict_comparison.json (32 cases, judged verdicts)

Writes data_cache/error_analysis_report.md.

Run (from backend/): python -m scripts.error_analysis
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, ".")

_DATA_DIR = Path(__file__).resolve().parent.parent / "data_cache"
SIGNALS_PATH = _DATA_DIR / "eval_judgments_with_signals.json"
RESULTS_PATH = _DATA_DIR / "real_judgment_eval_results.json"
VERDICTS_PATH = _DATA_DIR / "real_judgment_verdict_comparison.json"
OUT_PATH = _DATA_DIR / "error_analysis_report.md"

EXPECTED_CONDITION_BY_CATEGORY = {
    "escalation__criminal_matter": "criminal_matter_detected",
    "escalation__jurisdiction_mismatch": "jurisdiction_scope_mismatch",
}


def classify_error_mode(reason: str) -> str:
    """Bucket a judge's free-text mismatch/partial reason into a coarse
    error mode, purely by pattern-matching the judge's own wording -- this
    is NOT a re-review of the underlying judgment, so treat "other" as
    "needs a human to actually read it," not "uncategorizable."
    """
    r = reason.lower()
    if "ai dismissed" in r:
        return "ai_too_conservative"  # real court granted something, AI dismissed outright
    if r.startswith("both sides lost"):
        return "ai_too_liberal"  # AI granted relief the real court denied to everyone
    if "ai ordered" in r and ("court dismissed" in r or "court denied" in r):
        return "ai_too_liberal"
    if r.startswith("same side wins"):
        return "same_winner_different_relief"
    return "other_needs_manual_review"


def build_report() -> str:
    signals = {s["case_id"]: s for s in json.loads(SIGNALS_PATH.read_text(encoding="utf-8"))}
    results = {r["case_id"]: r for r in json.loads(RESULTS_PATH.read_text(encoding="utf-8"))}
    verdicts = json.loads(VERDICTS_PATH.read_text(encoding="utf-8"))

    lines: list[str] = []
    lines.append("# Real-Judgment Eval: Error Analysis")
    lines.append("")
    lines.append(
        "Generated by `scripts/error_analysis.py` from "
        "`data_cache/{eval_judgments_with_signals,real_judgment_eval_results,"
        "real_judgment_verdict_comparison}.json`. Do not hand-edit -- rerun "
        "the script after any eval refresh."
    )
    lines.append("")

    # ---- 0. dataset shape ----
    n_total = len(signals)
    n_escalation_test = sum(1 for s in signals.values() if s["escalation_expected"])
    n_civil = n_total - n_escalation_test
    n_judged = len(verdicts)
    languages = Counter(s["language"] for s in signals.values())

    lines.append("## Dataset shape")
    lines.append("")
    lines.append(f"- {n_total} real Indian Kanoon judgments total: {n_civil} ordinary civil "
                  f"cases + {n_escalation_test} escalation-safety-gate test cases.")
    lines.append(f"- {n_judged}/{n_civil} ordinary cases reached a judged AI-vs-real-court "
                  f"verdict (the rest didn't resolve cleanly -- see Structural findings below).")
    lines.append(f"- Language distribution: {dict(languages)}. "
                  + (f"All {n_total} sourced cases are English-language judgments, so this "
                     "dataset gives no signal on cross-language accuracy -- that's an untested "
                     "axis, not a confirmed non-issue." if len(languages) == 1 else ""))
    lines.append("")

    # ---- 1. confusion-matrix-style breakdown by dispute category ----
    by_cat: dict[str, Counter] = defaultdict(Counter)
    for v in verdicts:
        by_cat[v["category"]][v["verdict"]] += 1

    lines.append("## Verdict breakdown by dispute category")
    lines.append("")
    lines.append("| Category | n | match | partial | mismatch | match rate |")
    lines.append("|---|---|---|---|---|---|")
    totals = Counter()
    for cat in sorted(by_cat):
        c = by_cat[cat]
        n = sum(c.values())
        totals.update(c)
        rate = round(c["match"] / n, 2) if n else 0.0
        lines.append(f"| {cat} | {n} | {c['match']} | {c['partial']} | {c['mismatch']} | {rate} |")
    n_all = sum(totals.values())
    overall_rate = round(totals["match"] / n_all, 2) if n_all else 0.0
    lines.append(f"| **all** | **{n_all}** | **{totals['match']}** | **{totals['partial']}** "
                  f"| **{totals['mismatch']}** | **{overall_rate}** |")
    lines.append("")
    lines.append(
        "Also breaking out by the 4 dispute types DigiNyaya actually has registered "
        "(what each category above gets mapped onto -- see `CATEGORY_TO_DISPUTE_TYPE` in "
        "`scripts/run_real_judgment_eval.py`), since that mapping is a known approximation "
        "for tenancy/employment/property/partnership cases and worth checking separately:"
    )
    lines.append("")
    by_mapped: dict[str, Counter] = defaultdict(Counter)
    for v in verdicts:
        mapped = results[v["case_id"]]["mapped_dispute_type"]
        by_mapped[mapped][v["verdict"]] += 1
    lines.append("| Registered dispute_type | n | match | partial | mismatch | match rate |")
    lines.append("|---|---|---|---|---|---|")
    for mapped in sorted(by_mapped):
        c = by_mapped[mapped]
        n = sum(c.values())
        rate = round(c["match"] / n, 2) if n else 0.0
        lines.append(f"| {mapped} | {n} | {c['match']} | {c['partial']} | {c['mismatch']} | {rate} |")
    lines.append("")

    # ---- 2. error-mode classification for non-matches ----
    non_matches = [v for v in verdicts if v["verdict"] != "match"]
    mode_counts: Counter = Counter()
    mode_examples: dict[str, list] = defaultdict(list)
    for v in non_matches:
        mode = classify_error_mode(v["reason"])
        mode_counts[mode] += 1
        mode_examples[mode].append(v)

    lines.append("## Why the non-matches happened")
    lines.append("")
    lines.append(
        f"All {len(non_matches)} partial/mismatch verdicts, bucketed by pattern-matching the "
        "judge's own free-text reason (not a fresh manual re-review of each judgment)."
    )
    lines.append("")
    lines.append("| Error mode | count | share of non-matches |")
    lines.append("|---|---|---|")
    for mode, n in mode_counts.most_common():
        lines.append(f"| {mode} | {n} | {round(n / len(non_matches), 2)} |")
    lines.append("")

    if mode_counts["ai_too_conservative"] > mode_counts["ai_too_liberal"]:
        lines.append(
            f"**Dominant failure mode: too conservative.** {mode_counts['ai_too_conservative']} "
            f"of {len(non_matches)} non-matches are cases where the AI dismissed a claim the "
            f"real court actually granted (partly or in full), vs. only "
            f"{mode_counts['ai_too_liberal']} in the opposite direction (AI granted relief the "
            f"real court denied). This lines up with a known scripted rule in "
            "`app/agents/mediation.py`: the deterministic validator forces `clamped_ratio=0` "
            "(outright dismissal) whenever `respondent_strength >= claimant_strength`, "
            "discarding whatever nuanced relief the LLM itself proposed. It's a bias built "
            "into the decision logic, not a random LLM sampling issue -- consistent with why "
            "temperature fixes elsewhere in this eval didn't touch this particular failure mode."
        )
        lines.append("")

        cat_counts_in_mode = Counter(v["category"] for v in mode_examples["ai_too_conservative"])
        top_cat, top_n = cat_counts_in_mode.most_common(1)[0]
        cat_total = sum(1 for v in verdicts if v["category"] == top_cat)
        if top_n / len(mode_examples["ai_too_conservative"]) >= 0.5:
            lines.append(
                f"**And it's concentrated, not spread evenly:** {top_n} of "
                f"{len(mode_examples['ai_too_conservative'])} too-conservative cases are "
                f"`{top_cat}` ({top_n}/{cat_total} = {round(top_n / cat_total, 2)} of ALL judged "
                f"`{top_cat}` cases end in a wrongly-dismissed mismatch). For tenancy cases "
                "specifically, the pattern is almost always eviction/possession/rent-payment "
                "relief that the real court granted and the AI dismissed outright -- non-"
                "monetary or possession-type relief looks like exactly the kind of case "
                "`net_strength`'s binary dismiss-or-don't logic handles worst. This is the "
                "single most actionable finding in this report: fixing how "
                "`app/agents/mediation.py` handles possession/eviction relief (not just money) "
                f"would plausibly move more of the eval's accuracy than anything else currently "
                "visible in this dataset."
            )
            lines.append("")

    for mode, examples in mode_examples.items():
        lines.append(f"<details><summary>{mode} ({len(examples)} case(s))</summary>")
        lines.append("")
        for v in examples:
            lines.append(f"- `{v['case_id']}` ({v['category']}, verdict={v['verdict']}): {v['reason']}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if mode_counts["other_needs_manual_review"]:
        lines.append(
            "Note: `other_needs_manual_review` cases didn't match any of the pattern rules "
            "above cleanly -- e.g. `IK-EVAL-3677206` is labeled 'Opposite sides win' by the "
            "judge but its own reason text describes the AI and the real court both favoring "
            "the claimant, just at different amounts (closer to the "
            "`same_winner_different_relief` bucket). Flagged here as a real, observed judge-"
            "labeling inconsistency rather than silently reclassified."
        )
        lines.append("")

    # ---- 3. escalation safety-gate breakdown ----
    lines.append("## Escalation safety-gate cases (ground truth from sourcing, not LLM-judged)")
    lines.append("")
    esc_rows = []
    for cid, s in signals.items():
        if not s["escalation_expected"]:
            continue
        r = results.get(cid, {})
        expected = EXPECTED_CONDITION_BY_CATEGORY.get(s["category"])
        triggered = r.get("escalation_conditions") or []
        correct = r.get("escalated") and expected in triggered
        esc_rows.append((cid, s["category"], expected, r.get("escalated"), triggered, correct))
    n_correct = sum(1 for row in esc_rows if row[5])
    lines.append(f"{n_correct}/{len(esc_rows)} escalation test cases correctly escalated for "
                  "the expected reason.")
    lines.append("")
    lines.append("| case_id | category | expected condition | escalated? | triggered conditions | correct? |")
    lines.append("|---|---|---|---|---|---|")
    for cid, cat, expected, escalated, triggered, correct in esc_rows:
        lines.append(f"| {cid} | {cat} | {expected} | {escalated} | {', '.join(triggered) or '-'} "
                      f"| {'yes' if correct else 'NO'} |")
    lines.append("")

    # ---- 4. structural findings across all 46 ----
    civil_results = [results[cid] for cid, s in signals.items() if not s["escalation_expected"]]
    crashed = [r for r in civil_results if r.get("error")]
    unexpected_escalations = [r for r in civil_results if r.get("escalated")]
    unresolved = [r for r in civil_results if not r.get("escalated") and not r.get("resolved")]

    lines.append("## Structural findings (all 40 ordinary civil cases, pipeline-level)")
    lines.append("")
    lines.append(f"- Crashed: {len(crashed)}")
    lines.append(f"- Unexpectedly escalated (safety gate fired on an ordinary case): "
                  f"{len(unexpected_escalations)}")
    for r in unexpected_escalations:
        lines.append(f"  - `{r['case_id']}` ({r['category']}): {r.get('escalation_conditions')}")
    lines.append(f"- Reached the pipeline without escalating but never produced a resolution "
                  f"(e.g. escalated only at the later resolution step): {len(unresolved)}")
    lines.append("")

    lines.append("## Known dataset limitations (stated plainly, not hidden)")
    lines.append("")
    stale_count = sum(
        1 for v in verdicts
        if not results.get(v["case_id"], {}).get("resolved", True)
    )
    lines.append(
        f"- n={n_judged} judged cases is still small; every percentage above should be read as "
        "\"roughly\", not as a statistically tight estimate -- see "
        "`scripts/train_outcome_classifier.py`'s leave-one-out CV for the more rigorous "
        "treatment of the same data."
    )
    lines.append(
        "- `real_judgment_eval_results.json` and `real_judgment_verdict_comparison.json` come "
        f"from two separate pipeline runs (confirmed: {stale_count} judged case(s) show "
        "`resolved=False` in the results file yet carry a real judged `ai_relief`). Fields "
        "sourced only from the results file (confidence, precedents_retrieved) can be stale "
        f"for those {stale_count} case(s)."
    )
    lines.append(
        f"- All {n_total} sourced cases are English-language (see Dataset shape above) -- no "
        "evidence either way on Hindi/regional-language accuracy from this dataset."
    )
    lines.append(
        "- 4 of 7 real-world categories are mapped onto a DigiNyaya dispute_type that isn't a "
        "true match (tenancy/employment -> money_recovery, property/partnership -> "
        "contract_breach) -- see the by-mapped-type table above; accuracy on the true-fit "
        "categories (contract_disputes, consumer_complaints, small_claims_debt_recovery) "
        "should be trusted more than the approximated ones."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    report = build_report()
    OUT_PATH.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nWrote -> {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
